spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8080

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    root: INFO
    com.pioneer: DEBUG
